-- USERS
INSERT INTO USERS(user_id, first_name, last_name) VALUES (1, 'Ionut', 'Orsa');
INSERT INTO USERS(user_id, first_name, last_name) VALUES (2, 'Maria', 'Popescu');
INSERT INTO USERS(user_id, first_name, last_name) VALUES (3, 'Alexandru', 'Ionescu');
INSERT INTO USERS(user_id, first_name, last_name) VALUES (4, 'Elena', 'Constantin');
INSERT INTO USERS(user_id, first_name, last_name) VALUES (5, 'Andrei', 'Gheorghe');

-- PROCESSES
INSERT INTO PROCESSES(process_id, name) VALUES (1, 'VAT Clearing Script');
INSERT INTO PROCESSES(process_id, name) VALUES (2, 'Department Reclass Script');
INSERT INTO PROCESSES(process_id, name) VALUES (3, 'Prepaids Automation');
INSERT INTO PROCESSES(process_id, name) VALUES (4, 'GL Reconciliation Script');
INSERT INTO PROCESSES(process_id, name) VALUES (5, 'Month End Closing Script');

-- BATCHES, INPUTS, EXECUTIONS, OUTPUTS, ERRORS
INSERT INTO BATCHES(batch_id) VALUES (1);
INSERT INTO INPUTS(batch_id, input) VALUES (1, 'input_file_1.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (1, 5, 1, 1, 'SUCCESS', '2026-05-01 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (1, 'output_file_1.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (2);
INSERT INTO INPUTS(batch_id, input) VALUES (2, 'input_file_2.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (2, 2, 2, 2, 'FAILED', '2026-05-04 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (2, 'Currency conversion rate not found for USD/RON');
INSERT INTO BATCHES(batch_id) VALUES (3);
INSERT INTO INPUTS(batch_id, input) VALUES (3, 'input_file_3.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (3, 5, 4, 3, 'SUCCESS', '2026-05-04 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (3, 'output_file_3.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (4);
INSERT INTO INPUTS(batch_id, input) VALUES (4, 'input_file_4.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (4, 5, 4, 4, 'SUCCESS', '2026-05-04 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (4, 'output_file_4.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (5);
INSERT INTO INPUTS(batch_id, input) VALUES (5, 'input_file_5.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (5, 3, 4, 5, 'SUCCESS', '2026-05-07 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (5, 'output_file_5.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (6);
INSERT INTO INPUTS(batch_id, input) VALUES (6, 'input_file_6.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (6, 5, 3, 6, 'RUNNING', '2026-05-07 00:00:00');
INSERT INTO BATCHES(batch_id) VALUES (7);
INSERT INTO INPUTS(batch_id, input) VALUES (7, 'input_file_7.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (7, 5, 4, 7, 'SUCCESS', '2026-05-10 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (7, 'output_file_7.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (8);
INSERT INTO INPUTS(batch_id, input) VALUES (8, 'input_file_8.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (8, 1, 2, 8, 'SUCCESS', '2026-05-10 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (8, 'output_file_8.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (9);
INSERT INTO INPUTS(batch_id, input) VALUES (9, 'input_file_9.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (9, 3, 5, 9, 'FAILED', '2026-05-13 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (9, 'File is empty or contains no valid data');
INSERT INTO BATCHES(batch_id) VALUES (10);
INSERT INTO INPUTS(batch_id, input) VALUES (10, 'input_file_10.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (10, 3, 3, 10, 'SUCCESS', '2026-05-13 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (10, 'output_file_10.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (11);
INSERT INTO INPUTS(batch_id, input) VALUES (11, 'input_file_11.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (11, 1, 1, 11, 'SUCCESS', '2026-05-14 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (11, 'output_file_11.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (12);
INSERT INTO INPUTS(batch_id, input) VALUES (12, 'input_file_12.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (12, 1, 4, 12, 'SUCCESS', '2026-05-14 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (12, 'output_file_12.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (13);
INSERT INTO INPUTS(batch_id, input) VALUES (13, 'input_file_13.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (13, 1, 4, 13, 'SUCCESS', '2026-05-14 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (13, 'output_file_13.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (14);
INSERT INTO INPUTS(batch_id, input) VALUES (14, 'input_file_14.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (14, 2, 2, 14, 'FAILED', '2026-05-15 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (14, 'ERP connection timeout after 30 seconds');
INSERT INTO BATCHES(batch_id) VALUES (15);
INSERT INTO INPUTS(batch_id, input) VALUES (15, 'input_file_15.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (15, 2, 2, 15, 'SUCCESS', '2026-05-15 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (15, 'output_file_15.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (16);
INSERT INTO INPUTS(batch_id, input) VALUES (16, 'input_file_16.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (16, 3, 2, 16, 'FAILED', '2026-05-15 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (16, 'File format not supported. Expected .xlsx');
INSERT INTO BATCHES(batch_id) VALUES (17);
INSERT INTO INPUTS(batch_id, input) VALUES (17, 'input_file_17.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (17, 1, 2, 17, 'SUCCESS', '2026-05-17 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (17, 'output_file_17.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (18);
INSERT INTO INPUTS(batch_id, input) VALUES (18, 'input_file_18.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (18, 3, 4, 18, 'FAILED', '2026-05-17 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (18, 'File is empty or contains no valid data');
INSERT INTO BATCHES(batch_id) VALUES (19);
INSERT INTO INPUTS(batch_id, input) VALUES (19, 'input_file_19.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (19, 5, 3, 19, 'SUCCESS', '2026-05-19 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (19, 'output_file_19.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (20);
INSERT INTO INPUTS(batch_id, input) VALUES (20, 'input_file_20.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (20, 1, 1, 20, 'SUCCESS', '2026-05-19 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (20, 'output_file_20.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (21);
INSERT INTO INPUTS(batch_id, input) VALUES (21, 'input_file_21.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (21, 2, 5, 21, 'SUCCESS', '2026-05-19 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (21, 'output_file_21.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (22);
INSERT INTO INPUTS(batch_id, input) VALUES (22, 'input_file_22.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (22, 3, 4, 22, 'FAILED', '2026-05-30 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (22, 'Invalid GL account mapping found in row 45');
INSERT INTO BATCHES(batch_id) VALUES (23);
INSERT INTO INPUTS(batch_id, input) VALUES (23, 'input_file_23.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (23, 3, 5, 23, 'FAILED', '2026-05-30 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (23, 'Invalid GL account mapping found in row 45');
INSERT INTO BATCHES(batch_id) VALUES (24);
INSERT INTO INPUTS(batch_id, input) VALUES (24, 'input_file_24.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (24, 3, 5, 24, 'FAILED', '2026-06-01 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (24, 'Missing mandatory field: cost_center');
INSERT INTO BATCHES(batch_id) VALUES (25);
INSERT INTO INPUTS(batch_id, input) VALUES (25, 'input_file_25.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (25, 2, 2, 25, 'SUCCESS', '2026-06-02 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (25, 'output_file_25.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (26);
INSERT INTO INPUTS(batch_id, input) VALUES (26, 'input_file_26.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (26, 3, 2, 26, 'FAILED', '2026-06-02 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (26, 'Duplicate transaction detected for vendor ID 1023');
INSERT INTO BATCHES(batch_id) VALUES (27);
INSERT INTO INPUTS(batch_id, input) VALUES (27, 'input_file_27.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (27, 3, 5, 27, 'FAILED', '2026-06-02 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (27, 'Currency conversion rate not found for USD/RON');
INSERT INTO BATCHES(batch_id) VALUES (28);
INSERT INTO INPUTS(batch_id, input) VALUES (28, 'input_file_28.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (28, 3, 4, 28, 'FAILED', '2026-06-05 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (28, 'File format not supported. Expected .xlsx');
INSERT INTO BATCHES(batch_id) VALUES (29);
INSERT INTO INPUTS(batch_id, input) VALUES (29, 'input_file_29.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (29, 2, 2, 29, 'SUCCESS', '2026-06-05 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (29, 'output_file_29.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (30);
INSERT INTO INPUTS(batch_id, input) VALUES (30, 'input_file_30.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (30, 1, 5, 30, 'FAILED', '2026-06-08 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (30, 'Access denied: insufficient permissions for GL posting');
INSERT INTO BATCHES(batch_id) VALUES (31);
INSERT INTO INPUTS(batch_id, input) VALUES (31, 'input_file_31.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (31, 3, 3, 31, 'FAILED', '2026-06-09 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (31, 'Currency conversion rate not found for USD/RON');
INSERT INTO BATCHES(batch_id) VALUES (32);
INSERT INTO INPUTS(batch_id, input) VALUES (32, 'input_file_32.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (32, 1, 4, 32, 'SUCCESS', '2026-06-09 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (32, 'output_file_32.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (33);
INSERT INTO INPUTS(batch_id, input) VALUES (33, 'input_file_33.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (33, 5, 3, 33, 'FAILED', '2026-06-09 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (33, 'File is empty or contains no valid data');
INSERT INTO BATCHES(batch_id) VALUES (34);
INSERT INTO INPUTS(batch_id, input) VALUES (34, 'input_file_34.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (34, 1, 4, 34, 'RUNNING', '2026-06-10 00:00:00');
INSERT INTO BATCHES(batch_id) VALUES (35);
INSERT INTO INPUTS(batch_id, input) VALUES (35, 'input_file_35.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (35, 3, 2, 35, 'FAILED', '2026-06-11 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (35, 'Invalid GL account mapping found in row 45');
INSERT INTO BATCHES(batch_id) VALUES (36);
INSERT INTO INPUTS(batch_id, input) VALUES (36, 'input_file_36.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (36, 2, 3, 36, 'SUCCESS', '2026-06-12 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (36, 'output_file_36.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (37);
INSERT INTO INPUTS(batch_id, input) VALUES (37, 'input_file_37.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (37, 5, 3, 37, 'RUNNING', '2026-06-12 00:00:00');
INSERT INTO BATCHES(batch_id) VALUES (38);
INSERT INTO INPUTS(batch_id, input) VALUES (38, 'input_file_38.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (38, 3, 1, 38, 'SUCCESS', '2026-06-12 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (38, 'output_file_38.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (39);
INSERT INTO INPUTS(batch_id, input) VALUES (39, 'input_file_39.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (39, 4, 5, 39, 'FAILED', '2026-06-14 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (39, 'File is empty or contains no valid data');
INSERT INTO BATCHES(batch_id) VALUES (40);
INSERT INTO INPUTS(batch_id, input) VALUES (40, 'input_file_40.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (40, 1, 3, 40, 'SUCCESS', '2026-06-14 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (40, 'output_file_40.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (41);
INSERT INTO INPUTS(batch_id, input) VALUES (41, 'input_file_41.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (41, 1, 2, 41, 'SUCCESS', '2026-06-14 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (41, 'output_file_41.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (42);
INSERT INTO INPUTS(batch_id, input) VALUES (42, 'input_file_42.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (42, 1, 5, 42, 'SUCCESS', '2026-06-15 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (42, 'output_file_42.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (43);
INSERT INTO INPUTS(batch_id, input) VALUES (43, 'input_file_43.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (43, 4, 4, 43, 'SUCCESS', '2026-06-15 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (43, 'output_file_43.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (44);
INSERT INTO INPUTS(batch_id, input) VALUES (44, 'input_file_44.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (44, 5, 3, 44, 'SUCCESS', '2026-06-15 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (44, 'output_file_44.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (45);
INSERT INTO INPUTS(batch_id, input) VALUES (45, 'input_file_45.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (45, 5, 2, 45, 'FAILED', '2026-06-17 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (45, 'Invalid GL account mapping found in row 45');
INSERT INTO BATCHES(batch_id) VALUES (46);
INSERT INTO INPUTS(batch_id, input) VALUES (46, 'input_file_46.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (46, 3, 2, 46, 'SUCCESS', '2026-06-17 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (46, 'output_file_46.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (47);
INSERT INTO INPUTS(batch_id, input) VALUES (47, 'input_file_47.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (47, 5, 1, 47, 'FAILED', '2026-06-17 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (47, 'Access denied: insufficient permissions for GL posting');
INSERT INTO BATCHES(batch_id) VALUES (48);
INSERT INTO INPUTS(batch_id, input) VALUES (48, 'input_file_48.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (48, 2, 5, 48, 'SUCCESS', '2026-06-18 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (48, 'output_file_48.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (49);
INSERT INTO INPUTS(batch_id, input) VALUES (49, 'input_file_49.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (49, 2, 1, 49, 'SUCCESS', '2026-06-18 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (49, 'output_file_49.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (50);
INSERT INTO INPUTS(batch_id, input) VALUES (50, 'input_file_50.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (50, 4, 5, 50, 'SUCCESS', '2026-06-19 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (50, 'output_file_50.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (51);
INSERT INTO INPUTS(batch_id, input) VALUES (51, 'input_file_51.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (51, 3, 2, 51, 'FAILED', '2026-06-19 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (51, 'ERP connection timeout after 30 seconds');
INSERT INTO BATCHES(batch_id) VALUES (52);
INSERT INTO INPUTS(batch_id, input) VALUES (52, 'input_file_52.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (52, 4, 1, 52, 'SUCCESS', '2026-06-19 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (52, 'output_file_52.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (53);
INSERT INTO INPUTS(batch_id, input) VALUES (53, 'input_file_53.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (53, 1, 4, 53, 'SUCCESS', '2026-06-24 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (53, 'output_file_53.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (54);
INSERT INTO INPUTS(batch_id, input) VALUES (54, 'input_file_54.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (54, 2, 3, 54, 'SUCCESS', '2026-06-24 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (54, 'output_file_54.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (55);
INSERT INTO INPUTS(batch_id, input) VALUES (55, 'input_file_55.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (55, 1, 1, 55, 'SUCCESS', '2026-06-24 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (55, 'output_file_55.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (56);
INSERT INTO INPUTS(batch_id, input) VALUES (56, 'input_file_56.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (56, 5, 1, 56, 'SUCCESS', '2026-06-26 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (56, 'output_file_56.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (57);
INSERT INTO INPUTS(batch_id, input) VALUES (57, 'input_file_57.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (57, 4, 4, 57, 'SUCCESS', '2026-06-28 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (57, 'output_file_57.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (58);
INSERT INTO INPUTS(batch_id, input) VALUES (58, 'input_file_58.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (58, 2, 3, 58, 'SUCCESS', '2026-06-29 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (58, 'output_file_58.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (59);
INSERT INTO INPUTS(batch_id, input) VALUES (59, 'input_file_59.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (59, 2, 1, 59, 'RUNNING', '2026-06-29 00:00:00');
INSERT INTO BATCHES(batch_id) VALUES (60);
INSERT INTO INPUTS(batch_id, input) VALUES (60, 'input_file_60.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (60, 1, 4, 60, 'FAILED', '2026-06-30 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (60, 'Currency conversion rate not found for USD/RON');
INSERT INTO BATCHES(batch_id) VALUES (61);
INSERT INTO INPUTS(batch_id, input) VALUES (61, 'input_file_61.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (61, 2, 5, 61, 'SUCCESS', '2026-07-01 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (61, 'output_file_61.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (62);
INSERT INTO INPUTS(batch_id, input) VALUES (62, 'input_file_62.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (62, 5, 1, 62, 'FAILED', '2026-07-01 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (62, 'Access denied: insufficient permissions for GL posting');
INSERT INTO BATCHES(batch_id) VALUES (63);
INSERT INTO INPUTS(batch_id, input) VALUES (63, 'input_file_63.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (63, 1, 4, 63, 'FAILED', '2026-07-01 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (63, 'Currency conversion rate not found for USD/RON');
INSERT INTO BATCHES(batch_id) VALUES (64);
INSERT INTO INPUTS(batch_id, input) VALUES (64, 'input_file_64.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (64, 1, 3, 64, 'RUNNING', '2026-07-03 00:00:00');
INSERT INTO BATCHES(batch_id) VALUES (65);
INSERT INTO INPUTS(batch_id, input) VALUES (65, 'input_file_65.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (65, 4, 3, 65, 'FAILED', '2026-07-03 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (65, 'Row count mismatch between input and ERP confirmation');
INSERT INTO BATCHES(batch_id) VALUES (66);
INSERT INTO INPUTS(batch_id, input) VALUES (66, 'input_file_66.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (66, 2, 2, 66, 'FAILED', '2026-07-03 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (66, 'Invalid GL account mapping found in row 45');
INSERT INTO BATCHES(batch_id) VALUES (67);
INSERT INTO INPUTS(batch_id, input) VALUES (67, 'input_file_67.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (67, 1, 4, 67, 'FAILED', '2026-07-04 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (67, 'File is empty or contains no valid data');
INSERT INTO BATCHES(batch_id) VALUES (68);
INSERT INTO INPUTS(batch_id, input) VALUES (68, 'input_file_68.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (68, 1, 3, 68, 'SUCCESS', '2026-07-04 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (68, 'output_file_68.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (69);
INSERT INTO INPUTS(batch_id, input) VALUES (69, 'input_file_69.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (69, 3, 1, 69, 'SUCCESS', '2026-07-04 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (69, 'output_file_69.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (70);
INSERT INTO INPUTS(batch_id, input) VALUES (70, 'input_file_70.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (70, 3, 2, 70, 'SUCCESS', '2026-07-06 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (70, 'output_file_70.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (71);
INSERT INTO INPUTS(batch_id, input) VALUES (71, 'input_file_71.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (71, 5, 2, 71, 'FAILED', '2026-07-06 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (71, 'Access denied: insufficient permissions for GL posting');
INSERT INTO BATCHES(batch_id) VALUES (72);
INSERT INTO INPUTS(batch_id, input) VALUES (72, 'input_file_72.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (72, 4, 1, 72, 'FAILED', '2026-07-07 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (72, 'File format not supported. Expected .xlsx');
INSERT INTO BATCHES(batch_id) VALUES (73);
INSERT INTO INPUTS(batch_id, input) VALUES (73, 'input_file_73.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (73, 4, 4, 73, 'FAILED', '2026-07-08 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (73, 'Currency conversion rate not found for USD/RON');
INSERT INTO BATCHES(batch_id) VALUES (74);
INSERT INTO INPUTS(batch_id, input) VALUES (74, 'input_file_74.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (74, 3, 2, 74, 'SUCCESS', '2026-07-08 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (74, 'output_file_74.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (75);
INSERT INTO INPUTS(batch_id, input) VALUES (75, 'input_file_75.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (75, 3, 2, 75, 'FAILED', '2026-07-08 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (75, 'Invalid GL account mapping found in row 45');
INSERT INTO BATCHES(batch_id) VALUES (76);
INSERT INTO INPUTS(batch_id, input) VALUES (76, 'input_file_76.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (76, 5, 4, 76, 'FAILED', '2026-07-09 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (76, 'File format not supported. Expected .xlsx');
INSERT INTO BATCHES(batch_id) VALUES (77);
INSERT INTO INPUTS(batch_id, input) VALUES (77, 'input_file_77.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (77, 2, 1, 77, 'SUCCESS', '2026-07-09 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (77, 'output_file_77.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (78);
INSERT INTO INPUTS(batch_id, input) VALUES (78, 'input_file_78.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (78, 3, 2, 78, 'FAILED', '2026-07-10 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (78, 'ERP connection timeout after 30 seconds');
INSERT INTO BATCHES(batch_id) VALUES (79);
INSERT INTO INPUTS(batch_id, input) VALUES (79, 'input_file_79.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (79, 4, 5, 79, 'RUNNING', '2026-07-13 00:00:00');
INSERT INTO BATCHES(batch_id) VALUES (80);
INSERT INTO INPUTS(batch_id, input) VALUES (80, 'input_file_80.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (80, 3, 2, 80, 'RUNNING', '2026-07-13 00:00:00');
INSERT INTO BATCHES(batch_id) VALUES (81);
INSERT INTO INPUTS(batch_id, input) VALUES (81, 'input_file_81.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (81, 2, 5, 81, 'SUCCESS', '2026-07-13 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (81, 'output_file_81.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (82);
INSERT INTO INPUTS(batch_id, input) VALUES (82, 'input_file_82.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (82, 3, 2, 82, 'FAILED', '2026-07-14 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (82, 'Currency conversion rate not found for USD/RON');
INSERT INTO BATCHES(batch_id) VALUES (83);
INSERT INTO INPUTS(batch_id, input) VALUES (83, 'input_file_83.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (83, 2, 1, 83, 'SUCCESS', '2026-07-18 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (83, 'output_file_83.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (84);
INSERT INTO INPUTS(batch_id, input) VALUES (84, 'input_file_84.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (84, 3, 2, 84, 'SUCCESS', '2026-07-18 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (84, 'output_file_84.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (85);
INSERT INTO INPUTS(batch_id, input) VALUES (85, 'input_file_85.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (85, 1, 1, 85, 'FAILED', '2026-07-20 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (85, 'Invalid date format in column executed_at');
INSERT INTO BATCHES(batch_id) VALUES (86);
INSERT INTO INPUTS(batch_id, input) VALUES (86, 'input_file_86.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (86, 4, 5, 86, 'SUCCESS', '2026-07-20 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (86, 'output_file_86.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (87);
INSERT INTO INPUTS(batch_id, input) VALUES (87, 'input_file_87.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (87, 5, 3, 87, 'FAILED', '2026-07-21 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (87, 'Currency conversion rate not found for USD/RON');
INSERT INTO BATCHES(batch_id) VALUES (88);
INSERT INTO INPUTS(batch_id, input) VALUES (88, 'input_file_88.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (88, 1, 3, 88, 'SUCCESS', '2026-07-21 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (88, 'output_file_88.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (89);
INSERT INTO INPUTS(batch_id, input) VALUES (89, 'input_file_89.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (89, 3, 3, 89, 'SUCCESS', '2026-07-25 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (89, 'output_file_89.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (90);
INSERT INTO INPUTS(batch_id, input) VALUES (90, 'input_file_90.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (90, 1, 5, 90, 'SUCCESS', '2026-07-25 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (90, 'output_file_90.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (91);
INSERT INTO INPUTS(batch_id, input) VALUES (91, 'input_file_91.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (91, 4, 1, 91, 'SUCCESS', '2026-07-25 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (91, 'output_file_91.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (92);
INSERT INTO INPUTS(batch_id, input) VALUES (92, 'input_file_92.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (92, 5, 2, 92, 'RUNNING', '2026-07-26 00:00:00');
INSERT INTO BATCHES(batch_id) VALUES (93);
INSERT INTO INPUTS(batch_id, input) VALUES (93, 'input_file_93.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (93, 5, 1, 93, 'FAILED', '2026-07-28 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (93, 'Currency conversion rate not found for USD/RON');
INSERT INTO BATCHES(batch_id) VALUES (94);
INSERT INTO INPUTS(batch_id, input) VALUES (94, 'input_file_94.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (94, 1, 5, 94, 'SUCCESS', '2026-07-28 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (94, 'output_file_94.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (95);
INSERT INTO INPUTS(batch_id, input) VALUES (95, 'input_file_95.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (95, 1, 1, 95, 'SUCCESS', '2026-07-28 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (95, 'output_file_95.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (96);
INSERT INTO INPUTS(batch_id, input) VALUES (96, 'input_file_96.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (96, 2, 4, 96, 'RUNNING', '2026-07-29 00:00:00');
INSERT INTO BATCHES(batch_id) VALUES (97);
INSERT INTO INPUTS(batch_id, input) VALUES (97, 'input_file_97.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (97, 5, 2, 97, 'SUCCESS', '2026-07-29 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (97, 'output_file_97.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (98);
INSERT INTO INPUTS(batch_id, input) VALUES (98, 'input_file_98.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (98, 1, 4, 98, 'SUCCESS', '2026-07-29 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (98, 'output_file_98.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (99);
INSERT INTO INPUTS(batch_id, input) VALUES (99, 'input_file_99.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (99, 1, 2, 99, 'RUNNING', '2026-07-30 00:00:00');
INSERT INTO BATCHES(batch_id) VALUES (100);
INSERT INTO INPUTS(batch_id, input) VALUES (100, 'input_file_100.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (100, 4, 3, 100, 'SUCCESS', '2026-07-30 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (100, 'output_file_100.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (101);
INSERT INTO INPUTS(batch_id, input) VALUES (101, 'input_file_101.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (101, 3, 1, 101, 'SUCCESS', '2026-08-01 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (101, 'output_file_101.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (102);
INSERT INTO INPUTS(batch_id, input) VALUES (102, 'input_file_102.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (102, 5, 3, 102, 'SUCCESS', '2026-08-03 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (102, 'output_file_102.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (103);
INSERT INTO INPUTS(batch_id, input) VALUES (103, 'input_file_103.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (103, 4, 3, 103, 'SUCCESS', '2026-08-03 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (103, 'output_file_103.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (104);
INSERT INTO INPUTS(batch_id, input) VALUES (104, 'input_file_104.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (104, 3, 1, 104, 'FAILED', '2026-08-03 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (104, 'Currency conversion rate not found for USD/RON');
INSERT INTO BATCHES(batch_id) VALUES (105);
INSERT INTO INPUTS(batch_id, input) VALUES (105, 'input_file_105.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (105, 4, 1, 105, 'SUCCESS', '2026-08-05 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (105, 'output_file_105.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (106);
INSERT INTO INPUTS(batch_id, input) VALUES (106, 'input_file_106.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (106, 4, 1, 106, 'SUCCESS', '2026-08-08 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (106, 'output_file_106.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (107);
INSERT INTO INPUTS(batch_id, input) VALUES (107, 'input_file_107.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (107, 5, 2, 107, 'FAILED', '2026-08-08 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (107, 'Duplicate transaction detected for vendor ID 1023');
INSERT INTO BATCHES(batch_id) VALUES (108);
INSERT INTO INPUTS(batch_id, input) VALUES (108, 'input_file_108.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (108, 1, 5, 108, 'SUCCESS', '2026-08-09 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (108, 'output_file_108.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (109);
INSERT INTO INPUTS(batch_id, input) VALUES (109, 'input_file_109.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (109, 5, 2, 109, 'SUCCESS', '2026-08-09 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (109, 'output_file_109.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (110);
INSERT INTO INPUTS(batch_id, input) VALUES (110, 'input_file_110.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (110, 3, 2, 110, 'FAILED', '2026-08-13 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (110, 'Duplicate transaction detected for vendor ID 1023');
INSERT INTO BATCHES(batch_id) VALUES (111);
INSERT INTO INPUTS(batch_id, input) VALUES (111, 'input_file_111.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (111, 5, 3, 111, 'FAILED', '2026-08-13 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (111, 'Currency conversion rate not found for USD/RON');
INSERT INTO BATCHES(batch_id) VALUES (112);
INSERT INTO INPUTS(batch_id, input) VALUES (112, 'input_file_112.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (112, 1, 4, 112, 'FAILED', '2026-08-14 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (112, 'Invalid date format in column executed_at');
INSERT INTO BATCHES(batch_id) VALUES (113);
INSERT INTO INPUTS(batch_id, input) VALUES (113, 'input_file_113.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (113, 2, 1, 113, 'SUCCESS', '2026-08-14 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (113, 'output_file_113.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (114);
INSERT INTO INPUTS(batch_id, input) VALUES (114, 'input_file_114.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (114, 1, 2, 114, 'SUCCESS', '2026-08-15 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (114, 'output_file_114.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (115);
INSERT INTO INPUTS(batch_id, input) VALUES (115, 'input_file_115.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (115, 1, 4, 115, 'SUCCESS', '2026-08-15 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (115, 'output_file_115.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (116);
INSERT INTO INPUTS(batch_id, input) VALUES (116, 'input_file_116.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (116, 1, 5, 116, 'SUCCESS', '2026-08-16 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (116, 'output_file_116.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (117);
INSERT INTO INPUTS(batch_id, input) VALUES (117, 'input_file_117.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (117, 5, 2, 117, 'FAILED', '2026-08-16 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (117, 'Access denied: insufficient permissions for GL posting');
INSERT INTO BATCHES(batch_id) VALUES (118);
INSERT INTO INPUTS(batch_id, input) VALUES (118, 'input_file_118.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (118, 5, 2, 118, 'FAILED', '2026-08-16 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (118, 'Row count mismatch between input and ERP confirmation');
INSERT INTO BATCHES(batch_id) VALUES (119);
INSERT INTO INPUTS(batch_id, input) VALUES (119, 'input_file_119.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (119, 1, 1, 119, 'FAILED', '2026-08-19 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (119, 'Missing mandatory field: cost_center');
INSERT INTO BATCHES(batch_id) VALUES (120);
INSERT INTO INPUTS(batch_id, input) VALUES (120, 'input_file_120.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (120, 3, 4, 120, 'FAILED', '2026-08-19 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (120, 'ERP connection timeout after 30 seconds');
INSERT INTO BATCHES(batch_id) VALUES (121);
INSERT INTO INPUTS(batch_id, input) VALUES (121, 'input_file_121.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (121, 1, 2, 121, 'SUCCESS', '2026-08-19 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (121, 'output_file_121.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (122);
INSERT INTO INPUTS(batch_id, input) VALUES (122, 'input_file_122.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (122, 3, 4, 122, 'FAILED', '2026-08-20 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (122, 'Row count mismatch between input and ERP confirmation');
INSERT INTO BATCHES(batch_id) VALUES (123);
INSERT INTO INPUTS(batch_id, input) VALUES (123, 'input_file_123.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (123, 5, 3, 123, 'FAILED', '2026-08-22 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (123, 'Duplicate transaction detected for vendor ID 1023');
INSERT INTO BATCHES(batch_id) VALUES (124);
INSERT INTO INPUTS(batch_id, input) VALUES (124, 'input_file_124.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (124, 2, 5, 124, 'FAILED', '2026-08-27 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (124, 'Access denied: insufficient permissions for GL posting');
INSERT INTO BATCHES(batch_id) VALUES (125);
INSERT INTO INPUTS(batch_id, input) VALUES (125, 'input_file_125.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (125, 1, 3, 125, 'FAILED', '2026-08-27 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (125, 'Duplicate transaction detected for vendor ID 1023');
INSERT INTO BATCHES(batch_id) VALUES (126);
INSERT INTO INPUTS(batch_id, input) VALUES (126, 'input_file_126.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (126, 5, 4, 126, 'FAILED', '2026-08-27 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (126, 'File is empty or contains no valid data');
INSERT INTO BATCHES(batch_id) VALUES (127);
INSERT INTO INPUTS(batch_id, input) VALUES (127, 'input_file_127.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (127, 1, 4, 127, 'FAILED', '2026-08-28 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (127, 'Invalid date format in column executed_at');
INSERT INTO BATCHES(batch_id) VALUES (128);
INSERT INTO INPUTS(batch_id, input) VALUES (128, 'input_file_128.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (128, 3, 2, 128, 'SUCCESS', '2026-08-28 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (128, 'output_file_128.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (129);
INSERT INTO INPUTS(batch_id, input) VALUES (129, 'input_file_129.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (129, 1, 3, 129, 'SUCCESS', '2026-08-29 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (129, 'output_file_129.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (130);
INSERT INTO INPUTS(batch_id, input) VALUES (130, 'input_file_130.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (130, 5, 2, 130, 'SUCCESS', '2026-08-29 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (130, 'output_file_130.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (131);
INSERT INTO INPUTS(batch_id, input) VALUES (131, 'input_file_131.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (131, 4, 2, 131, 'SUCCESS', '2026-08-30 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (131, 'output_file_131.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (132);
INSERT INTO INPUTS(batch_id, input) VALUES (132, 'input_file_132.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (132, 1, 2, 132, 'FAILED', '2026-08-30 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (132, 'Invalid date format in column executed_at');
INSERT INTO BATCHES(batch_id) VALUES (133);
INSERT INTO INPUTS(batch_id, input) VALUES (133, 'input_file_133.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (133, 3, 5, 133, 'SUCCESS', '2026-08-31 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (133, 'output_file_133.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (134);
INSERT INTO INPUTS(batch_id, input) VALUES (134, 'input_file_134.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (134, 5, 4, 134, 'FAILED', '2026-09-01 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (134, 'Duplicate transaction detected for vendor ID 1023');
INSERT INTO BATCHES(batch_id) VALUES (135);
INSERT INTO INPUTS(batch_id, input) VALUES (135, 'input_file_135.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (135, 2, 5, 135, 'SUCCESS', '2026-09-02 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (135, 'output_file_135.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (136);
INSERT INTO INPUTS(batch_id, input) VALUES (136, 'input_file_136.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (136, 3, 4, 136, 'SUCCESS', '2026-09-02 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (136, 'output_file_136.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (137);
INSERT INTO INPUTS(batch_id, input) VALUES (137, 'input_file_137.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (137, 4, 1, 137, 'SUCCESS', '2026-09-03 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (137, 'output_file_137.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (138);
INSERT INTO INPUTS(batch_id, input) VALUES (138, 'input_file_138.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (138, 3, 2, 138, 'RUNNING', '2026-09-03 00:00:00');
INSERT INTO BATCHES(batch_id) VALUES (139);
INSERT INTO INPUTS(batch_id, input) VALUES (139, 'input_file_139.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (139, 5, 2, 139, 'FAILED', '2026-09-04 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (139, 'Currency conversion rate not found for USD/RON');
INSERT INTO BATCHES(batch_id) VALUES (140);
INSERT INTO INPUTS(batch_id, input) VALUES (140, 'input_file_140.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (140, 5, 2, 140, 'SUCCESS', '2026-09-05 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (140, 'output_file_140.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (141);
INSERT INTO INPUTS(batch_id, input) VALUES (141, 'input_file_141.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (141, 4, 1, 141, 'SUCCESS', '2026-09-05 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (141, 'output_file_141.xlsx');
INSERT INTO BATCHES(batch_id) VALUES (142);
INSERT INTO INPUTS(batch_id, input) VALUES (142, 'input_file_142.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (142, 3, 2, 142, 'FAILED', '2026-09-05 00:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (142, 'Currency conversion rate not found for USD/RON');
INSERT INTO BATCHES(batch_id) VALUES (143);
INSERT INTO INPUTS(batch_id, input) VALUES (143, 'input_file_143.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (143, 3, 3, 143, 'SUCCESS', '2026-09-06 00:00:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (143, 'output_file_143.xlsx');

-- Process with no executions (for LEFT JOIN query testing)
INSERT INTO PROCESSES(process_id, name) VALUES (6, 'Lease Accounting Script');

-- RETRY SCENARIOS - multiple executions per batch

-- Batch 294: process 3, 3 executions
INSERT INTO BATCHES(batch_id) VALUES (294);
INSERT INTO INPUTS(batch_id, input) VALUES (294, 'input_file_294.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (294, 3, 2, 294, 'FAILED', '2026-08-06 13:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (294, 'Currency conversion rate not found for USD/RON');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (295, 3, 2, 294, 'FAILED', '2026-08-06 13:15:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (295, 'ERP connection timeout after 30 seconds');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (296, 3, 2, 294, 'SUCCESS', '2026-08-06 13:30:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (296, 'output_file_296.xlsx');

-- Batch 295: process 3, 2 executions
INSERT INTO BATCHES(batch_id) VALUES (295);
INSERT INTO INPUTS(batch_id, input) VALUES (295, 'input_file_295.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (297, 3, 1, 295, 'FAILED', '2026-08-05 11:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (297, 'File is empty or contains no valid data');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (298, 3, 1, 295, 'FAILED', '2026-08-05 11:15:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (298, 'Row count mismatch between input and ERP confirmation');

-- Batch 296: process 5, 3 executions
INSERT INTO BATCHES(batch_id) VALUES (296);
INSERT INTO INPUTS(batch_id, input) VALUES (296, 'input_file_296.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (299, 5, 3, 296, 'FAILED', '2026-06-01 13:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (299, 'Row count mismatch between input and ERP confirmation');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (300, 5, 3, 296, 'FAILED', '2026-06-01 13:15:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (300, 'Duplicate transaction detected for vendor ID 1023');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (301, 5, 3, 296, 'SUCCESS', '2026-06-01 13:30:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (301, 'output_file_301.xlsx');

-- Batch 297: process 1, 2 executions
INSERT INTO BATCHES(batch_id) VALUES (297);
INSERT INTO INPUTS(batch_id, input) VALUES (297, 'input_file_297.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (302, 1, 2, 297, 'FAILED', '2026-09-08 09:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (302, 'File format not supported. Expected .xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (303, 1, 2, 297, 'SUCCESS', '2026-09-08 09:15:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (303, 'output_file_303.xlsx');

-- Batch 298: process 4, 3 executions
INSERT INTO BATCHES(batch_id) VALUES (298);
INSERT INTO INPUTS(batch_id, input) VALUES (298, 'input_file_298.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (304, 4, 4, 298, 'FAILED', '2026-05-17 14:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (304, 'Invalid GL account mapping found in row 45');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (305, 4, 4, 298, 'FAILED', '2026-05-17 14:15:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (305, 'Currency conversion rate not found for USD/RON');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (306, 4, 4, 298, 'FAILED', '2026-05-17 14:30:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (306, 'Invalid date format in column executed_at');

-- Batch 299: process 3, 4 executions
INSERT INTO BATCHES(batch_id) VALUES (299);
INSERT INTO INPUTS(batch_id, input) VALUES (299, 'input_file_299.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (307, 3, 5, 299, 'FAILED', '2026-06-21 13:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (307, 'ERP connection timeout after 30 seconds');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (308, 3, 5, 299, 'FAILED', '2026-06-21 13:15:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (308, 'Currency conversion rate not found for USD/RON');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (309, 3, 5, 299, 'FAILED', '2026-06-21 13:30:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (309, 'Invalid GL account mapping found in row 45');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (310, 3, 5, 299, 'SUCCESS', '2026-06-21 13:45:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (310, 'output_file_310.xlsx');

-- Batch 300: process 2, 2 executions
INSERT INTO BATCHES(batch_id) VALUES (300);
INSERT INTO INPUTS(batch_id, input) VALUES (300, 'input_file_300.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (311, 2, 3, 300, 'FAILED', '2026-07-12 15:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (311, 'Currency conversion rate not found for USD/RON');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (312, 2, 3, 300, 'SUCCESS', '2026-07-12 15:15:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (312, 'output_file_312.xlsx');

-- Batch 301: process 5, 3 executions
INSERT INTO BATCHES(batch_id) VALUES (301);
INSERT INTO INPUTS(batch_id, input) VALUES (301, 'input_file_301.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (313, 5, 1, 301, 'FAILED', '2026-08-20 11:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (313, 'Missing mandatory field: cost_center');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (314, 5, 1, 301, 'FAILED', '2026-08-20 11:15:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (314, 'File is empty or contains no valid data');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (315, 5, 1, 301, 'FAILED', '2026-08-20 11:30:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (315, 'Row count mismatch between input and ERP confirmation');

-- Batch 302: process 1, 2 executions
INSERT INTO BATCHES(batch_id) VALUES (302);
INSERT INTO INPUTS(batch_id, input) VALUES (302, 'input_file_302.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (316, 1, 2, 302, 'FAILED', '2026-09-03 14:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (316, 'File format not supported. Expected .xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (317, 1, 2, 302, 'SUCCESS', '2026-09-03 14:15:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (317, 'output_file_317.xlsx');

-- Batch 303: process 3, 3 executions
INSERT INTO BATCHES(batch_id) VALUES (303);
INSERT INTO INPUTS(batch_id, input) VALUES (303, 'input_file_303.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (318, 3, 3, 303, 'FAILED', '2026-08-17 14:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (318, 'Missing mandatory field: cost_center');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (319, 3, 3, 303, 'FAILED', '2026-08-17 14:15:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (319, 'Currency conversion rate not found for USD/RON');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (320, 3, 3, 303, 'SUCCESS', '2026-08-17 14:30:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (320, 'output_file_320.xlsx');

-- Batch 304: process 4, 2 executions
INSERT INTO BATCHES(batch_id) VALUES (304);
INSERT INTO INPUTS(batch_id, input) VALUES (304, 'input_file_304.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (321, 4, 1, 304, 'FAILED', '2026-05-13 12:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (321, 'ERP connection timeout after 30 seconds');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (322, 4, 1, 304, 'FAILED', '2026-05-13 12:15:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (322, 'File is empty or contains no valid data');

-- Batch 305: process 5, 4 executions
INSERT INTO BATCHES(batch_id) VALUES (305);
INSERT INTO INPUTS(batch_id, input) VALUES (305, 'input_file_305.xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (323, 5, 4, 305, 'FAILED', '2026-08-02 15:00:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (323, 'File is empty or contains no valid data');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (324, 5, 4, 305, 'FAILED', '2026-08-02 15:15:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (324, 'File format not supported. Expected .xlsx');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (325, 5, 4, 305, 'FAILED', '2026-08-02 15:30:00');
INSERT INTO ERRORS(execution_id, error_msg) VALUES (325, 'Invalid GL account mapping found in row 45');
INSERT INTO EXECUTIONS(execution_id, process_id, user_id, batch_id, status, executed_at) VALUES (326, 5, 4, 305, 'SUCCESS', '2026-08-02 15:45:00');
INSERT INTO OUTPUTS(execution_id, output) VALUES (326, 'output_file_326.xlsx');
